glslc src/shader.vert -o bin/shaderVert.spv
glslc src/shader.frag -o bin/shaderFrag.spv
glslc src/blend.vert -o bin/blendVert.spv
glslc src/blend.frag -o bin/blendFrag.spv
glslc src/presentFrame.vert -o bin/presentFrameVert.spv
glslc src/presentFrame.frag -o bin/presentFrameFrag.spv
glslc src/blur_v.vert -o bin/blur_vVert.spv
glslc src/blur_v.frag -o bin/blur_vFrag.spv
glslc src/blur_h.vert -o bin/blur_hVert.spv
glslc src/blur_h.frag -o bin/blur_hFrag.spv
glslc src/inverstedHull.vert -o bin/inverstedHullVert.spv
glslc src/inverstedHull.frag -o bin/inverstedHullFrag.spv
glslc src/cloud.vert -o bin/cloudVert.spv
glslc src/cloud.frag -o bin/cloudFrag.spv
glslc src/baseShader.vert -o bin/baseShaderVert.spv
glslc src/baseShader.frag -o bin/baseShaderFrag.spv
glslc src/g_buffer.vert -o bin/g_bufferVert.spv
glslc src/g_buffer.frag -o bin/g_bufferFrag.spv
glslc src/cloud.comp -o bin/cloudComp.spv

